### ISSUE TITLE
Width not always exact

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#141]
When running `pageres todomvc.com 1000x1000` the resulting image is `1006x1977`.

**Comment by pranny** [comment]
I faced similar issue. It looks like it is due to the fact that some websites use javascript to align elements exactly. So, I found a library that does postpone script executions for sometime. https://github.com/DeviaVir/pixelratio-screenshots/blob/master/pixelratio.js. Maybe this patch would be required.
