### ISSUE TITLE
Limited CSS Selectors

### ISSUE THREAD

**Issue by influential** [sindresorhus/pageres#231]
It looks to me like the selector functionality is adequate for a majority of use cases. But for any scenario where you want to select a portion of a page that doesn't immediately come after a parent/container element, there are restrictions. Would it make sense to create an updated function that returns the rectangle that includes all elements returned by the CSS selector? That is, when a set of elements is returned. If a query that selects only one element is used, it would function the same as it does now, but if there are multiple, then the user could possibly include a range parameter for the elements (or have access to documentation on how to use the nth-child pseudo class), and the rectangle would include all of those elements.

To kind of make this more clear, if I had a list...
`<ul>`
`<li></li>`
`<li></li>`
`<li></li>`
`<li></li>`
`</ul>`

I wouldn't be able to select the 2nd and 3rd elements of the list and specifically screenshot them. I could only either select the entire list, or any one list item individually.

Am I correct?

I'd be willing to take a crack at it.

**Comment by influential** [comment]
To clarify, I originally looked at this old commit and assumed some things: https://github.com/sindresorhus/pageres/blob/edfb910279fa44f064738a0771611b398c4222e1/converter.js

But it looks like that file no longer exists in the master project.

**Comment by SamVerschueren** [comment]
The selector stuff is defined in [screenshot-stream](https://github.com/kevva/screenshot-stream/blob/master/stream.js#L91-L97).

So it's because `screenshot-stream` uses `querySelector` which you can ask for the bounding rectangle. But because `querySelector` only returns the first element, only that element will pop up in the result.

There is something like `querySelectorAll`. The thing is that this returns an array of elements and you can't ask for the bounding rectangle. So in this case, you would have to manually calculate the bounding rectangle by iterating over all the selected elements and calculate the rectangle yourself (shouldn't be that hard).

But what would you do if someone selects all the odd elements in a list? He might expect that we somehow magically extract all those elements and output those the a file.

// @sindresorhus @kevva

**Comment by influential** [comment]
If they didn't want to see the even numbered elements at all, you could maybe gather all the boundary points and use canvas or something to fill in the whitespace. (Just speculating)

But really it then becomes a question of how specific of functionality does this library need to provide.

For my use case I was able to use PhantomJS to pull DOM element positions and then was able to get the screenshots I needed. The more I think about it the more I feel like my use case is very unique though. So maybe what would be most helpful to others would just be a table with CSS selector info that would help people find the CSS syntax they need for odd selector use cases.

**Comment by sindresorhus** [comment]
Yeah, I think this is too obscure to support and would not be what I'd expect.

**Comment by SamVerschueren** [comment]
Actually, at the moment with the custom css support, it is possible to capture the odd elements.

```html
<ul id="foo">
    <li>Foo</li>
    <li>Bar</li>
    <li>Baz</li>
    <li>Baa</li>
</ul>
```

```
$ pageres mypage.com --selector="#foo" --css="ul#foo > li:nth-child(even) { display: none; }"
```

Tested it with the yeoman website

```
$ pageres yeoman.io --selector=".team" --css=".team > li:nth-child(even) { display: none; }"
```

![yeoman io-1366x768](https://cloud.githubusercontent.com/assets/1913805/12868413/754389da-cd06-11e5-9f9f-48b190fa6cd8.png)

Be creative ;).
