### ISSUE TITLE
PDF support?

### ISSUE THREAD

**Issue by jozsi** [sindresorhus/pageres#232]
Hello,

What is preventing `pageres` from exporting as `pdf`? According to the `README`, only `png` and `jpg` formats are supported. Supplying `pdf` as `format` results in an empty file, without any error message.

**Comment by SamVerschueren** [comment]
It's because `pageres` uses [screenshot-stream](https://github.com/kevva/screenshot-stream) which uses [`renderBase64`](https://github.com/kevva/screenshot-stream/blob/master/stream.js#L99). As documented by PhantomJS, [renderBase64](http://phantomjs.org/api/webpage/method/render-base64.html) does not support `pdf`.

So support for `pdf` should be added in `screenshot-stream`.

**Comment by SamVerschueren** [comment]
Workaround for pdf (works with temporary file)
http://stackoverflow.com/questions/11408332/phantomjs-exported-pdf-to-stdout

Can work together with [tempfile](https://github.com/sindresorhus/tempfile).

**Comment by sindresorhus** [comment]
Open a feature request on PhantomJS to get support for PDF in `renderBase64`. We'll expose it if added there. Not interested in adding dirty workarounds for something that isn't really the goal of this module.

**Comment by SamVerschueren** [comment]
https://github.com/ariya/phantomjs/issues/13823
