### ISSUE TITLE
When a file exists, append something random to the filename and try again.

### ISSUE THREAD

**Issue by corysimmons** [sindresorhus/pageres#239]
https://github.com/sindresorhus/pageres/issues/238#issuecomment-183599937

:+1: :100:

**Comment by SamVerschueren** [comment]
I would rather prefer an incrementing number

- file.png
- file (1).png
- file (2).png

**Comment by corysimmons** [comment]
:+1: 

Prefer this style though: `file-1.png`

**Comment by SamVerschueren** [comment]
Shouldn't we follow the default style for duplicate filenames? Would be more consistent, no?

**Comment by corysimmons** [comment]
Why don't we just provide an increment number and nothing else? Then users can decide in their filename template:

`<%= url %> (<%= increment %>)` or `<%= url %>-<%= increment %>`

**Comment by t1st3** [comment]
Why not something with date and time, like the file names in the `DCIM` folder of cameras/phones, like:
`file-yyyymmdd-hhmmss.png`, for example `file-20160828-114325.png`?

**Comment by vasco-santos** [comment]
Hello,

@corysimmons Considering url=yeoman.io, your suggestion leads to yeoman.io(), yeoman.io(1), yeoman.io(2). As a consequence of the template being provided by the user, we cannot control this strange notation "()".

I think that pageres should provide a default behavior for the incremental notation (a flag that automatically inserts "(increment)" if the increment exists, otherwise does not insert anything for the incrementation). If the user intends to make another notation, he sets the default delimiter notation as false and changes the template as @corysimmons suggested. However, the user has to take into account the possible problem that I mentioned before.

I made a pull request with my proposed solution.
