### ISSUE TITLE
Use nightmarejs (which use electron) instead of PhantomJS

### ISSUE THREAD

**Issue by MoOx** [sindresorhus/pageres#267]
PhantomJS engine is kind of outdated and a lot of modern websites are rendered like shit (hello flexbox support).
Using NightmareJS (which use electron under the hood) might be a solid option.

**Comment by SamVerschueren** [comment]
I guess we are going to wait for headless chrome. Unless @sindresorhus has another opinion :).

**Comment by sindresorhus** [comment]
Last time I checked out NightmareJS it required a bunch of stuff in your Travis file to be able to run headlessly on Linux. Has that changed? Because requiring that is a pretty leaky abstraction and forces everything that uses Pageres to document how to do that. Right now Pageres *just works*. Pageres now uses PhantomJS 2 which is at least on a somewhat recent version of WebKit and it works pretty ok. I think I'd rather wait on headless Chrome.

**Comment by MoOx** [comment]
You mean this https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md#travis-ci?

**Comment by sindresorhus** [comment]
Yes
